/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    ReposCards: typeof import('./src/components/ReposCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPage: typeof import('./src/components/SearchPage.vue')['default']
    SearchRepos: typeof import('./src/components/SearchRepos.vue')['default']
  }
}
