/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackGround: typeof import('./src/components/BackGround.vue')['default']
    CardsFiller: typeof import('./src/components/CardsFiller.vue')['default']
    CarouselComponent: typeof import('./src/components/CarouselComponent.vue')['default']
    ChatRepo: typeof import('./src/components/ChatRepo.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    ReposCards: typeof import('./src/components/ReposCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchPage: typeof import('./src/components/SearchPage.vue')['default']
    SearchRepos: typeof import('./src/components/SearchRepos.vue')['default']
  }
}
